### ISSUE TITLE
Doubt on how to query inventory for many products

### ISSUE THREAD

**Issue by aecioneto** [Caryley/Laravel-Inventory#13]
Hello, I am using this package to manage inventory of products.
I have a view listing some products details and I would like to add a column with the inventory.
How to query the most recent inventory quantity for all products at once, please?

**Comment by talelmishali** [comment]
Hello @aecioneto , 

You have few ways to go about it, it depends. Can you share with us how do you query the products you passing to the view now?

**Comment by aecioneto** [comment]
Sure!
Model name is Product. In controller, I get all products via AJAX call from DataTables:

public function dtAll()
    {
        $query = DB::table('produtos');

        return DataTables::of($query)->make();
    }

I tried getting all Products and related inventory and the query works, but whenever there is a change in inventory quantity,  I get more than one row for the Product. So, the issue is to get only the most recent quantity, I know.
When I tried getting this via Model, it takes forever LOL

Here is the code I tried:
    public function dtAll()
    {
        $last = DB::table('inventories')
        ->select(DB::raw('MAX(id) as last_id'), 'inventoriable_id')
        ->where('inventoriable_type', '=', 'App\Models\Produto')
        ->groupBy('inventoriable_id');

        $inventory = DB::table('inventories')
        ->joinSub($last, 'last', function($join) {
            $join->on('inventories.id', '=', 'last.last_id');
        })
        ->select('inventories.inventoriable_id','inventories.quantity');

        $query = DB::table('produtos')
        ->leftJoinSub($inventory, 'i', function($join) {
            $join->on('produtos.id', '=', 'i.inventoriable_id');
        })
        ->select('produtos.id', 'produtos.nome', 'i.quantity');

        return DataTables::of($query)->make();
    }

**Comment by talelmishali** [comment]
@aecioneto sorry for being away for a few days, I closed the issue as it's more of a Q&A than a package issue. 

Regardless, I am working on a PR to improve this behavior following the suggestion on #11. You can check the progress of it on the [develop](https://github.com/Caryley/Laravel-Inventory/tree/develop) branch, I am looking to take advantage of the [Has One Of Many](https://laravel.com/docs/9.x/eloquent-relationships#has-one-of-many) approach with ```latestOfMany``` relationship.
